apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-deployment
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointment-service
  template:
    metadata:
      labels:
        app: appointment-service
    spec:
      containers:
      - name: appointment-service
        image: 794038257645.dkr.ecr.ap-southeast-1.amazonaws.com/ecr-repo-appointment:latest
        ports:
          - containerPort: 3002
        env:
          - name: PORT
            value: "3002"
---
apiVersion: v1
kind: Service
metadata:
  name: appointment-service-service
  namespace: production
spec:
  type: LoadBalancer
  selector:
    app: appointment-service
  ports:
    - port: 80
      targetPort: 3002