apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-deployment
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: 794038257645.dkr.ecr.ap-southeast-1.amazonaws.com/ecr-repo-notification:latest
        ports:
          - containerPort: 3004
        env:
          - name: PORT
            value: "3004"
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service-service
  namespace: production
spec:
  type: LoadBalancer
  selector:
    app: notification-service
  ports:
    - port: 80
      targetPort: 3004